
import { PageInfo } from './types';

export const BROCHURE_PAGES: PageInfo[] = [
 { id: 1, title: "Admission Kit Cover", imageUrl: "/pages/page_1.jpg" },
  { id: 2, title: "Enquiry Form", imageUrl: "/pages/page_2.jpg" },
  { id: 3, title: "Office Use Checklist", imageUrl: "/pages/page_3.jpg" },
  { id: 4, title: "Why MS? The Right Choice", imageUrl: "/pages/page_4.jpg" },
  { id: 5, title: "Chairman's Message", imageUrl: "/pages/page_5.jpg" },
  { id: 6, title: "Mission, Vision & Values", imageUrl: "/pages/page_6.jpg" },
  { id: 7, title: "Why MS? (Details)", imageUrl: "/pages/page_7.jpg" },
  { id: 8, title: "Academic Excellence", imageUrl: "/pages/page_8.jpg" },
  { id: 9, title: "Tarbiyah-Based Education", imageUrl: "/pages/page_9.jpg" },
  { id: 10, title: "MYJO Smart Curriculum", imageUrl: "/pages/page_10.jpg" },
  { id: 11, title: "MYJO Teaching Approach", imageUrl: "/pages/page_11.jpg" },
  { id: 12, title: "5D Thinking Model", imageUrl: "/pages/page_12.jpg" },
  { id: 13, title: "5D Thinking Impact", imageUrl: "/pages/page_13.jpg" },
  { id: 14, title: "Core Faculty Profile", imageUrl: "/pages/page_14.jpg" },
  { id: 15, title: "Faculty Bios - Group A", imageUrl: "/pages/page_15.jpg" },
  { id: 16, title: "Faculty Bios - Group B", imageUrl: "/pages/page_16.jpg" },
  { id: 17, title: "Faculty Bios - Group C", imageUrl: "/pages/page_17.jpg" },
  { id: 18, title: "Faculty Bios - Group D", imageUrl: "/pages/page_18.jpg" },
  { id: 19,title: "Faculty Bios - Group D", imageUrl: "/pages/page_19.jpg"},
  { id: 20, title: "Infrastructure & Student Safety", imageUrl: "/pages/page_20.jpg" },
  { id: 21, title: "Campus Design", imageUrl: "/pages/page_21.jpg" },
  { id: 22, title: "Safety & Emergency", imageUrl: "/pages/page_22.jpg" },
  { id: 23, title: "Co-Scholastic Achievements", imageUrl: "/pages/page_23.jpg" },
  { id: 24, title: "Sports - Karate", imageUrl: "/pages/page_24.jpg" },
  { id: 25, title: "Sports - Boxing", imageUrl: "/pages/page_25.jpg" },
  { id: 26, title: "Sports - Judo & Skating", imageUrl: "/pages/page_26.jpg" },
  { id: 27, title: "World Teen Parliament", imageUrl: "/pages/page_27.jpg" },
  { id: 28, title: "Science Olympiad", imageUrl: "/pages/page_28.jpg" },
  { id: 29, title: "MS Hifz Academy", imageUrl: "/pages/page_29.jpg" },
  { id: 30, title: "Young Innovators", imageUrl: "/pages/page_30.jpg" },
  { id: 31, title: "Drawing & Creative Arts", imageUrl: "/pages/page_31.jpg" },
  { id: 32, title: "Space & Quran Literacy", imageUrl: "/pages/page_32.jpg" },
  { id: 33, title: "Mega Mind Mapping", imageUrl: "/pages/page_33.jpg" },
  { id: 34, title: "Handwriting Laurels", imageUrl: "/pages/page_34.jpg" },
  { id: 35, title: "Fee Structure", imageUrl: "/pages/page_35.jpg" },
  { id: 36, title: "Guidance is Key", imageUrl: "/pages/page_36.jpg" },
  { id: 37, title: "Intermediate Results", imageUrl: "/pages/page_37.jpg" },
  { id: 38, title: "National Footprint - IITs", imageUrl: "/pages/page_38.jpg" },
  { id: 39, title: "Medical Footprint - NEET", imageUrl: "/pages/page_39.jpg" },
  { id: 40, title: "Admission Closure Process", imageUrl: "/pages/page_40.jpg" },
  { id: 41, title: "Thank You / Back Cover", imageUrl: "/pages/page_41 .jpg" }
];
