
import { PageInfo } from './types';

export const BROCHURE_PAGES: PageInfo[] = [
  { id: 1, title: "Admission Kit Cover", category: "Intro", imageUrl: "/pages/page_1.jpg" },
  { id: 2, title: "Enquiry Form", category: "Forms", imageUrl: "/pages/page_2.jpg" },
  { id: 3, title: "Office Use Checklist", category: "Forms", imageUrl: "/pages/page_3.jpg" },
  { id: 4, title: "Why MS? The Right Choice", category: "Philosophy", imageUrl: "/pages/page_4.jpg" },
  { id: 5, title: "Chairman's Message", category: "Leadership", imageUrl: "/pages/page_5.jpg" },
  { id: 6, title: "Mission, Vision & Values", category: "Philosophy", imageUrl: "/pages/page_6.jpg" },
  { id: 7, title: "Why MS? (Details)", category: "Philosophy", imageUrl: "/pages/page_7.jpg" },
  { id: 8, title: "Academic Excellence", category: "Academics", imageUrl: "/pages/page_8.jpg" },
  { id: 9, title: "Tarbiyah-Based Education", category: "Academics", imageUrl: "/pages/page_9.jpg" },
  { id: 10, title: "MYJO Smart Curriculum", category: "Curriculum", imageUrl: "/pages/page_10.jpg" },
  { id: 11, title: "MYJO Teaching Approach", category: "Curriculum", imageUrl: "/pages/page_11.jpg" },
  { id: 12, title: "5D Thinking Model", category: "Curriculum", imageUrl: "/pages/page_12.jpg" },
  { id: 13, title: "5D Thinking Impact", category: "Curriculum", imageUrl: "/pages/page_13.jpg" },
  { id: 14, title: "Core Faculty Profile", category: "Faculty", imageUrl: "/pages/page_14.jpg" },
  { id: 15, title: "Faculty Bios - Group A", category: "Faculty", imageUrl: "/pages/page_15.jpg" },
  { id: 16, title: "Faculty Bios - Group B", category: "Faculty", imageUrl: "/pages/page_16.jpg" },
  { id: 17, title: "Faculty Bios - Group C", category: "Faculty", imageUrl: "/pages/page_17.jpg" },
  { id: 18, title: "Faculty Bios - Group D", category: "Faculty", imageUrl: "/pages/page_18.jpg" },
  { id: 19, title: "Infrastructure & Student Safety", category: "Campus", imageUrl: "/pages/page_19.jpg" },
  { id: 20, title: "Campus Design", category: "Campus", imageUrl: "/pages/page_20.jpg" },
  { id: 21, title: "Safety & Emergency", category: "Campus", imageUrl: "/pages/page_21.jpg" },
  { id: 22, title: "Co-Scholastic Achievements", category: "Achievements", imageUrl: "/pages/page_22.jpg" },
  { id: 23, title: "Sports - Karate", category: "Sports", imageUrl: "/pages/page_23.jpg" },
  { id: 24, title: "Sports - Boxing", category: "Sports", imageUrl: "/pages/page_24.jpg" },
  { id: 25, title: "Sports - Judo & Skating", category: "Sports", imageUrl: "/pages/page_25.jpg" },
  { id: 26, title: "World Teen Parliament", category: "Achievements", imageUrl: "/pages/page_26.jpg" },
  { id: 27, title: "Science Olympiad", category: "Achievements", imageUrl: "/pages/page_27.jpg" },
  { id: 28, title: "MS Hifz Academy", category: "Special", imageUrl: "/pages/page_28.jpg" },
  { id: 29, title: "Young Innovators", category: "Achievements", imageUrl: "/pages/page_29.jpg" },
  { id: 30, title: "Drawing & Creative Arts", category: "Achievements", imageUrl: "/pages/page_30.jpg" },
  { id: 31, title: "Space & Quran Literacy", category: "Special", imageUrl: "/pages/page_31.jpg" },
  { id: 32, title: "Mega Mind Mapping", category: "Special", imageUrl: "/pages/page_32.jpg" },
  { id: 33, title: "Handwriting Laurels", category: "Achievements", imageUrl: "/pages/page_33.jpg" },
  { id: 34, title: "Fee Structure", category: "Admission", imageUrl: "/pages/page_34.jpg" },
  { id: 35, title: "Guidance is Key", category: "Admission", imageUrl: "/pages/page_35.jpg" },
  { id: 36, title: "Intermediate Results", category: "Results", imageUrl: "/pages/page_36.jpg" },
  { id: 37, title: "National Footprint - IITs", category: "Results", imageUrl: "/pages/page_37.jpg" },
  { id: 38, title: "Medical Footprint - NEET", category: "Results", imageUrl: "/pages/page_38.jpg" },
  { id: 39, title: "Admission Closure Process", category: "Admission", imageUrl: "/pages/page_39.jpg" },
  { id: 40, title: "Thank You / Back Cover", category: "Intro", imageUrl: "/pages/page_40.jpg" }
];
